UNDEFINED_ADDRESSING_MODE = 'Und'
INH  = 'Inh'                # ''        -
IMM  = 'Imm'                # 'ii' 
IMM16= 'I16'               # 'jjkk'    -
DIR  = 'Dir'                # 'dd'
EXT  = 'Ext'                # 'hhll'    -
INDX = 'Xin'                # 'ff'      -
INDY = 'Yin'                # 'ff'      -
REL  = 'Rel'                # 'rr'
DIR_MSK = 'DMk'             # 'ddmm'    -
INDX_MSK = 'XMk'            # 'ffmm'    -    
INDY_MSK = 'YMk'           # 'ffmm'    -
DIR_MSK_REL = 'DMR'        # 'ddmmrr' -
INDX_MSK_REL = 'XMR'       # 'ffmmrr' -
INDY_MSK_REL = 'YMR'      # 'ffmmrr' -
